CustomerApp/Models/ErrorViewModel.cs
namespace CustomerApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CustomerApp/ViewModels/MOTCustomerStatusViewData.cs
using CustomerApp.Interfaces;
using MOTStatusWebApi.Data;
using MOTStatusWebApi.Models;

namespace CustomerApp.ViewModels
{
    public class MOTCustomerStatusViewData : IMOTCustomerStatusViewData
    {
        public IEnumerable<MOTTestCertificateDetails> mOTTestCertificateDetails { get; set; }
        public MOTTestCertificateDetails mOTTestCertificateDetail { get; set; }
        public MOTStatusDetails mOTStatusDetails { get; set; }
        public bool RegistrationValidationError { get; set; }
        public bool RegistrationFormatError { get; set; }
        public bool RegistrationNotFoundError { get; set; }
        public bool ConfirmNotSelectedError { get; set; }
        public List<string> FailureList { get; set; }
    }
}

CustomerApp/Controllers/HomeController.cs
using CustomerApp.Interfaces;
using CustomerApp.Models;
using Microsoft.AspNetCore.Mvc;
using MOTStatusWebApi.Data;
using Newtonsoft.Json;
using System.Diagnostics;
using System.Text.RegularExpressions;

namespace CustomerApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IMOTCustomerStatusViewData _viewData;

        HttpClient client = new HttpClient();
        string url = "https://localhost:7132/api/MOTStatusDetails/11/registration?registration=";
        public HomeController(ILogger<HomeController> logger, IMOTCustomerStatusViewData viewData)
        {
            _logger = logger;
            _viewData = viewData;
        }

        public IActionResult Index()
        {
            return View(_viewData); 
        }

        [HttpPost]
        public async Task<IActionResult> Index(string registration)
        {
            if (registration == null)
            {
                _viewData.RegistrationValidationError = true;          
                return View(_viewData);
            }

            registration = registration.Replace(" ", "");

            var regexValidation = VehicleRegEx(registration);

            if (!regexValidation)
            {
                _viewData.RegistrationFormatError = true;
                return View(_viewData);
            }

            try
            {
                var carDetail = JsonConvert.DeserializeObject<MOTStatusDetails>(await client.GetStringAsync(url + registration));             
                return RedirectToAction("DetailConfirmation", carDetail );
            }
            catch (Exception ex)
            {
                _viewData.RegistrationNotFoundError = true;
                return View(_viewData);
            }        
        }

        public IActionResult DetailConfirmation(MOTStatusDetails carDetails)
        {
            string formatReg = FormatReg(carDetails.RegistrationNumber);
            carDetails.RegistrationNumber = formatReg;
            _viewData.mOTStatusDetails = carDetails;
            return View(_viewData);
        }

        [HttpPost]
        public IActionResult DetailConfirmation(string confirm, MOTStatusDetails detail)
        {
            if(confirm == null)
            {
                string formatReg = FormatReg(detail.RegistrationNumber);
                detail.RegistrationNumber = formatReg;
                _viewData.mOTStatusDetails = detail;
                _viewData.ConfirmNotSelectedError = true;
                return View(_viewData);
            }

            if(confirm == "Yes")
            {
                return RedirectToAction("VehicleDetail", detail);
            }else if(confirm == "No"){
                return RedirectToAction("Index");
            }

            return View(confirm);
        }

        public IActionResult VehicleDetail(MOTStatusDetails detail)
        {
            string formatReg = FormatReg(detail.RegistrationNumber);
            detail.RegistrationNumber = formatReg;
            detail.DateOfRegistration = FormatDate(detail.DateOfRegistration);
            detail.DateOfLastMOT = FormatDate(detail.DateOfLastMOT);
            detail.DateOfLastV5C = FormatDate(detail.DateOfLastV5C);
            detail.TaxDueDate = FormatDate(detail.TaxDueDate);
            detail.MOTDueDate = FormatDate(detail.MOTDueDate);

            return View(detail);
        }

        private string FormatDate(string detailsDate)
        {
            DateTime date = DateTime.Parse(detailsDate);
            var result = date.ToString("d/MMMM/yyyy").Replace("/"," ");

            return (result);
        }

        private string FormatReg(string registration)
        {
            var result = registration.Insert(4, " ");
            return result;
        }

        private bool VehicleRegEx(string registration)
        {
            var regExIsValid = Regex.IsMatch(registration, @"^(?=.{1,7})(([a-zA-Z]?){1,3}(\d){1,4}([a-zA-Z]?){1,3})$");

            return regExIsValid;
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CustomerApp/Controllers/MOTHistoryController.cs
using CustomerApp.Interfaces;
using Microsoft.AspNetCore.Mvc;
using MOTStatusWebApi.Interfaces;

namespace CustomerApp.Controllers
{
    public class MOTHistoryController : Controller
    {
        private readonly IMOTCustomerStatusViewData _viewData;
        private readonly IMOTTestCertificateDetailsRepository _testDetailsRepository;
        private readonly IMOTStatusDetailsRepository _statusDetailsRepository;

        public MOTHistoryController(IMOTCustomerStatusViewData viewData, IMOTTestCertificateDetailsRepository testDetailsRepository, IMOTStatusDetailsRepository statusDetailsRepository)
        {
           _viewData = viewData;
            _testDetailsRepository = testDetailsRepository;
            _statusDetailsRepository = statusDetailsRepository;
        }

        public IActionResult MOTHistoryIndex(string vehicleId, string dateOfRegistration, string dateOfLastMOT)
        {
            _viewData.mOTTestCertificateDetails = _testDetailsRepository.GetTestCertificateDetails().Where(d => d.VehicleID == vehicleId).ToList().OrderByDescending(x => x.MOTTestNumber);

            _viewData.mOTStatusDetails = _statusDetailsRepository.GetStatusDetails().Where(d => d.VehicleID == vehicleId).FirstOrDefault();

            _viewData.mOTStatusDetails.DateOfRegistration = dateOfRegistration;
            _viewData.mOTStatusDetails.DateOfLastMOT = dateOfLastMOT;

            

            foreach (var item in _viewData.mOTTestCertificateDetails)
            {
                item.DateOfLastMOT = FormatDate(item.DateOfLastMOT);
                item.MOTDueDate = FormatDate(item.MOTDueDate);

                var mileage = Int32.Parse(item.OdometerReading);
                item.OdometerReading = String.Format("{0:#,##0.##}", mileage);

                if(item.TestResult == "FAIL")
                {
                    List<string> failureList = FormatFailureList(item.ReasonForFailure);
                    _viewData.FailureList = failureList;
                }

              
             
                
            }

            
            

            return View(_viewData);
        }

        private List<string> FormatFailureList(string mOTFailures)
        {
            List<string> result = mOTFailures.Split(',').ToList();

            return(result);
        }

        private string FormatDate(string detailsDate)
        {
            DateTime date = DateTime.Parse(detailsDate);
            var result = date.ToString("d/MMMM/yyyy").Replace("/", " ");

            return (result);
        }
    }
}

CustomerApp/Views/Home/DetailConfirmation.cshtml
@*@model MOTStatusWebApi.Data.MOTStatusDetails
*@

@using CustomerApp.ViewModels
@model MOTCustomerStatusViewData

<head>
    <link href="~/css/DetailConfirmation.css" rel="stylesheet" type="text/css"/>
</head>

<div class="container p-3 mt-4 bg-body-secondary">
    <div class="row pt-4">
        <div class="col-2"></div>
        <div class="col-8">
            <h2><strong>Is this the vehicle you are looking for?</strong></h2><br />
            <table>
                <tr>
                   <td class="attribute">Registration number</td>
                   <td>
                       <div id="regPlate">
                            <h4>@Model.mOTStatusDetails.RegistrationNumber</h4>   
                       </div>
                   </td>
                </tr>
                <tr>
                    <td class="attribute">Make</td>
                    <td>@Model.mOTStatusDetails.Make</td>
                </tr>
                <tr>
                    <td class="attribute">Colour</td>
                    <td>@Model.mOTStatusDetails.VehicleColour</td>
                </tr>
            </table>
        </div>
        <div class="col-2"></div>
    </div>
</div>

<form method="post">

    @if(Model.ConfirmNotSelectedError == false)
    {
     <div class="container p-3 mt-0 bg-body-secondary">
         <div class="row pt-0">
               <div class="col-2"></div>
               <div class="col-6">
                  <input type="radio" id="Yes" name="confirm" value="Yes"/>
                  <label for="Yes" style="margin-right:60px;">Yes</label>
                  <input type="radio" id="No" name="confirm" value="No"/>
                  <label for="No">No, search again</label>
               </div>
               <div class="col-4"></div>       
         </div>        
    </div>
    }else if(Model.ConfirmNotSelectedError == true)
    {
        <div class="container p-3 mt-0 bg-body-secondary">
         <div class="row pt-0">
               <div class="col-2"></div>
               <div class="col-6" style="border-left-style: solid; border-left-color: red; border-width: 5px">
                   <h5 style="color:red; margin-left:10px"><strong>Select yes if this is the correct vehicle or no to search again</strong></h5>
                  <input type="radio" id="Yes" name="confirm" value="Yes"/>
                  <label for="Yes" style="margin-right:60px;" >Yes</label>
                  <input type="radio" id="No" name="confirm" value="No"/>
                  <label for="No">No, search again</label>
               </div>
               <div class="col-4"></div>       
         </div>        
        </div>
    }

    <div class="container p-0 mt-0 bg-body-secondary" >
        <div class="row pt-0">
            <div class="col-2"></div>
            <div class="col-2">
                <button class="button" id="buttonactive" type="submit" onclick="location.href='@Url.Action("DetailConfirmation", "Home",Model)'">Continue</button>    
            </div>
        </div>
    </div>  
</form>

 <div class="container p-0 mt-4 bg-body-secondary">
        <div class="row pt-0">
            <div class="col-2"></div>
            <div class="col-8">
                <div style="display:inline">
                   <img id="arrowIcon" src="~/images/icons8-right-arrow-64.png" width="23" height="23"/>
                   <button id="IncorrectVehicleDetails" onclick="IncorrectVehicleDetails()"> Incorrect vehicle details?</button>
                </div>
                <div id="incorrectVehicleDetailsInfo" style="display:none;">
                  <p style="margin-left:10px; margin-top:10px;">
                      If your vehicle details are incorrect you may need to <a href="">update them</a>.
                  </p>
                 
                </div>
           </div>
      </div>
</div>

<script>
    function IncorrectVehicleDetails() {

      var x = document.getElementById("incorrectVehicleDetailsInfo");
          if (x.style.display === "none") {
            x.style.display = "block";
          } else {
            x.style.display = "none";
          }

    var arrow = document.getElementById("arrowIcon");
     if(arrow.src === 'https://localhost:7131/images/icons8-right-arrow-64.png'){
         arrow.src = 'https://localhost:7131/images/icons8-drop-down-64.png';
     } else {
         arrow.src = 'https://localhost:7131/images/icons8-right-arrow-64.png';
     }
}

</script>

CustomerApp/Views/Home/Index.cshtml
 
@using CustomerApp.ViewModels
@model MOTCustomerStatusViewData

@{
    ViewData["Title"] = "Home Page";
}

<head>
    <link href="~/css/Index.css" rel="stylesheet" type="text/css"/>
</head>


<div class="container p-3 mt-4 bg-body-secondary">
    <div class="row pt-4">
        <div class="col-2"></div>
        <div class="col-8">
            <h1><strong>Enter the registration of the</strong></h1>
            <h1><strong>vehicle</strong></h1><br />

            <form method="post">

                @if(Model.RegistrationValidationError == false && Model.RegistrationFormatError == false && Model.RegistrationNotFoundError == false)
                {
                  <div class="mb-3">
                       <h3><strong>Registration number (number plate)</strong></h3>
                       <p style="font-size:20px">For example, CU57ABC or ABC1234</p>
                    <input class="regInput" type="text" name="registration" maxlength="10"/>
                  </div>
                }else if(Model.RegistrationValidationError == true && Model.RegistrationFormatError == false)
                {
                  <div style="border-left-style: solid; border-left-color: red; border-width: 5px">
                       <h3 style="margin-left:10px"><strong>Registration number (number plate)</strong></h3>
                       <p style="font-size:20px; margin-left:10px">For example, CU57ABC or ABC1234</p>
                       <h4 style="color:red; margin-left:10px"><strong>Provide the vehicle registration</strong></h4>  
                      <div class="mb-3">
                        <input class="errorRegInput" type="text" name="registration" maxlength="10" />
                      </div>
                    </div>
                }else if(Model.RegistrationValidationError == false && Model.RegistrationFormatError == true)
                {
                    <div style="border-left-style: solid; border-left-color: red; border-width: 5px">
                       <h3 style="margin-left:10px"><strong>Registration number (number plate)</strong></h3>
                       <p style="font-size:20px; margin-left:10px">For example, CU57ABC or ABC1234</p>
                       <h4 style="color:red; margin-left:10px"><strong>Provide a valid vehicle registration</strong></h4>  
                      <div class="mb-3">
                        <input class="errorRegInput" type="text" name="registration" maxlength="10" />
                      </div>
                    </div>
                }else if(Model.RegistrationNotFoundError = true)
                {
                    <div style="border-left-style: solid; border-left-color: red; border-width: 5px">
                       <h3 style="margin-left:10px"><strong>Registration number (number plate)</strong></h3>
                       <p style="font-size:20px; margin-left:10px">For example, CU57ABC or ABC1234</p>
                       <h4 id="vehicle-not-found-error" style="color:red; margin-left:10px"><strong>Vehicle registration was not found</strong></h4>  
                      <div class="mb-3">
                        <input class="errorRegInput" type="text" name="registration" maxlength="10" />
                      </div>
                    </div>
                }

                <br />
               <button class="button" id="buttonactive" type="submit">Continue</button>
               
            </form>
        </div>
        <div class="col-2"></div>
    </div>
</div>

<script>

 
</script>

CustomerApp/Views/Home/VehicleDetail.cshtml
@model MOTStatusWebApi.Data.MOTStatusDetails

@{
Layout = "~/Views/Shared/_VehicleDetailLayout.cshtml";
}

<head>
    <link href="~/css/VehicleDetail.css" rel="stylesheet" type="text/css"/>
</head>

<div style="margin-top:40px;">
    <h4 id="regPlate">@Model.RegistrationNumber</h4>
</div>

<div class="container p-0 mt-2 bg-body-secondary">
    <div class="row">
        <div class="col-2"></div>

        @if(Model.Taxed == true)
        {          
            <div class="col-4" id="greenCard">
                <h2 style="margin-top:15px;"><span style="font-family: Arial Unicode MS, Lucida Grande">&#10004;</span> Taxed</h2>
                <h5>Tax due:</h5>
                <h5 style="margin-bottom:25px;">@Model.TaxDueDate</h5>           
            </div>
        }else if(Model.Taxed == false)
        {
            <div class="col-4" id="redCard">
                <h2 style="margin-top:15px;"><span style="font-family: Arial Unicode MS, Lucida Grande">&#10008;</span> Not Taxed</h2>
                <h5>Tax due:</h5>
                <h5 style="margin-bottom:25px;">@Model.TaxDueDate</h5>
            </div>
        }

        @if(Model.MOTed == true)
        {
            <div class="col-4" id="greenCard">
              <h2 style="margin-top:10px;"><span style="font-family: Arial Unicode MS, Lucida Grande">&#10004;</span> MOT</h2>
              <h5>Expires:</h5>
              <h5>@Model.MOTDueDate</h5>
            </div>

        }else if(Model.MOTed == false)
        {
             <div class="col-4" id="redCard">
              <h2 style="margin-top:10px;"><span style="font-family: Arial Unicode MS, Lucida Grande">&#10008;</span> No MOT</h2>
              <h5>Expires:</h5>
              <h5>@Model.MOTDueDate</h5>
            </div>
        }
    </div>
</div>

<div class="container p-0 mt-0 bg-body-secondary">
    <div class="row">
        <div class="col-2"></div>
        <div class="col-4">
             
            <div style="display:inline">
               <img id="arrowIcon" src="~/images/icons8-right-arrow-64.png" width="23" height="23"/>
               <button id="IncorrectTaxStatus" onclick="IncorrectTaxStatus()"> Incorrect tax status?</button>
            </div>
        
              <div id="taxStatusInfo" style="display:none;">
                  <p style="margin-left:10px; margin-top:10px;">
                      If you've just taxed or made a SORN it can take up to 5 working days
                      for your status to update. You can check with your bank/building society
                      to confirm your payment was successful.</p>
                  <p style="margin-left:10px; margin-top:10px;">
                      If the tax status is still incorrect after 5 working days <a href="" style="color:#0059b3">contact DVLA</a>
                  </p>
              </div>
        </div>
        <div class="col-4">
            <div style="display:inline">
                <img id="MOTarrowIcon" src="~/images/icons8-right-arrow-64.png" width="23" height="23"/>
                <button id="IncorrectMOTStatus" onclick="IncorrectMOTStatus()"> Incorrect MOT status?</button>
            </div>
            <div id="MOTStatusInfo" style="display:none">
                <p style="margin-left:10px; margin-top:10px;">
                    If the MOT status is incorrect it can take up to 5
                    working days for your status to update.
                </p>
                 <p style="margin-left:10px; margin-top:10px;">
                     If the MOT status is still incorrect after 5 working days <a href="">contact DVLA</a>
                </p>
            </div>
              
        </div>
    </div>
</div>

<div class="container p-0 mt-4 bg-body-secondary">
    <div class="row">
        <div class="col-2"></div>
            <div class="col-8">
                <div style="display:inline">
                    <img src="~/images/exclamation.png" width="30" height="30" />
                    <span><strong>If you've just bought this vehicle the <a href="">tax</a> or <a href="">SORN</a> doesn't come with it. 
                        You'll need to <a href="">tax</a> it before driving it.</strong></span>
                </div>
            </div>
    </div>
</div>

<div class="container p-0 mt-4 bg-body-secondary">
    <div class="row">    
        <div class="col-2"></div>   
        <div class="col-5">
                  <h5><strong>Vehicle Details</strong></h5>
              <table>
                <tr>
                    <td class="attribute">Vehicle make</td>
                    <td>@Model.Make</td>
                </tr>
                <tr>
                    <td class="attribute">Date of first registration</td>
                    <td>@Model.DateOfRegistration</td>
                </tr>
                <tr>
                    <td class="attribute">Cylinder Capacity</td>
                    <td>@Model.CylinderCapacity cc</td>
                </tr>
                 <tr>
                    <td class="attribute">CO<a style="font-size:10px; font-weight: bold;">2</a> Emissions</td>
                    <td>@Model.CO2Emissions g/km</td>
                </tr>
                 <tr>
                    <td class="attribute">Fuel Type</td>
                    <td>@Model.FuelType</td>
                </tr> <tr>
                    <td class="attribute">Euro status</td>
                    <td>@Model.EuroStatus</td>
                </tr>
                 <tr>
                    <td class="attribute">Real driving emissions (RDE)</td>
                    <td>@Model.RealDrivingEmissions</td>
                </tr>
                 <tr>
                    <td class="attribute">Export marker</td>
                    <td>@Model.ExportMarker</td>
                </tr>
                 <tr>
                    <td class="attribute">Vehicle Status</td>
                    <td>@Model.VehicleStatus</td>
                </tr>
                <tr>
                    <td class="attribute">Vehicle Colour</td>
                    <td>@Model.VehicleColour</td>
                </tr>
                 <tr>
                    <td class="attribute">Vehicle type approval</td>
                    <td>@Model.VehicleTypeApproval</td>
                </tr>
                 <tr>
                    <td class="attribute">Wheel plan</td>
                    <td>@Model.WheelPlan</td>
                </tr>
                 <tr>
                    <td class="attribute">Revenue weight</td>
                    <td>@Model.RevenueWeight</td>
                </tr>
                 <tr>
                    <td class="attribute">Date of last V5C</td>
                    <td>@Model.DateOfLastV5C</td>
                </tr>
                 <tr>
                    <td class="attribute">Tax due date</td>
                    <td>@Model.TaxDueDate</td>
                </tr>
                 <tr>
                    <td class="attribute">Date of last MOT</td>
                    <td>@Model.DateOfLastMOT</td>
                </tr>
                 <tr>
                    <td class="attribute">MOT due date</td>
                    <td>@Model.MOTDueDate</td>
                </tr>
            </table>
            <div style="border-bottom: 1pt solid black;">
                 <h5 style="margin-top:30px;"><strong>View the tax rates for this vehicle</strong></h5>
                 <p>If you have the latest 11 digit reference number from the V5C registration
                     certificate (logbook) you can <a href="">view the tax rates for this vehicle.</a>
                 </p>
            </div>
             <div class="container p-0 mt-4 bg-body-secondary">
                <div class="row pt-0">
                    <div class="col-8">
                        <div style="display:inline">
                           <img id="incorrectDetailarrowIcon" src="~/images/icons8-right-arrow-64.png" width="23" height="23"/>
                           <button id="IncorrectVehicleDetails" onclick="IncorrectVehicleDetails()"> Incorrect vehicle details?</button>
                        </div>
                        <div id="incorrectVehicleDetailsInfo" style="display:none;">
                          <p style="margin-left:10px; margin-top:10px;">
                              If your vehicle details are incorrect you may need to <a href="">update them</a>.
                          </p>           
                        </div>
                   </div>
                </div>
             </div><br />

              <button id="button" onclick="location.href='@Url.Action("Index", "Home")'">Return to GOV.UK</button>

         </div>
         <div class="col-3">
             <div id="DVLAServices">
                 <h5 style="margin-top:10px;"><strong>DVLA services</strong></h5>
                 <div id="serviceLink"><a href="">Tax your vehicle</a><br /></div>
                 <div id="serviceLink"><a href="">Get a vehicle logbook (V5C)</a><br /></div>
                 <div id="serviceLink"><a href="">Driver and vehicles account: sign in or set up</a><br /></div>
                 <div id="serviceLink"><a href="">Register your vehicle as off the road (SORN)</a><br /></div>
                 <div id="serviceLink"><a href="">Change your vehicle's tax class</a><br /></div>
                 <div id="serviceLink"><a href="">Tell DVLA you've sold, transferred or bought a vehicle</a><br /></div>
                 <div id="serviceLink"><a href="">Update your vehicle's address</a><br /></div>
                 <div id="serviceLink"><a href="">Report an untaxed vehicle</a><br /></div>
                 <div id="serviceLink"><a href="">Check you're not buying a stolen vehicle</a><br /></div>
                 <div id="serviceLink"><a href="">Tax your vehicle</a><br /></div>
                 <div id="serviceLink"><a href="">Check if your vehicle can run on E10 petrol</a><br /></div>
             </div><br /><br />
             <div id="DVLAServices">
                 <h5 style="margin-top:10px;"><strong>DVSA services</strong></h5>
                 <div id="serviceLink"> @Html.ActionLink("Check the MOT history of a vehicle","MOTHistoryIndex","MOTHistory", new {vehicleId = @Model.VehicleID, dateOfRegistration = @Model.DateOfRegistration, dateOfLastMOT = @Model.DateOfLastMOT})</div>
                 <div id="serviceLink"><a href="">Get MOT reminders</a><br /></div>
                 <div id="serviceLink"><a href="">Report a vehicle with no MOT</a><br /></div>
                 <div id="serviceLink"><a href="">MOTs for vehicles registered in Nothern Ireland</a><br /></div>
                 <div id="serviceLink"><a href="">Check if a vehicle, part or accessory has been recalled</a><br /></div>
             </div>
         </div>
    </div>
</div>


<script>
    function IncorrectTaxStatus() {
      var x = document.getElementById("taxStatusInfo");
          if (x.style.display === "none") {
            x.style.display = "block";
          } else {
            x.style.display = "none";
          }

    var arrow = document.getElementById("arrowIcon");
     if(arrow.src === 'https://localhost:7131/images/icons8-right-arrow-64.png'){
         arrow.src = 'https://localhost:7131/images/icons8-drop-down-64.png';
     } else {
         arrow.src = 'https://localhost:7131/images/icons8-right-arrow-64.png';
     }
}

    function IncorrectMOTStatus() {
      var x = document.getElementById("MOTStatusInfo");
          if (x.style.display === "none") {
            x.style.display = "block";
          } else {
            x.style.display = "none";
          }

    var arrow = document.getElementById("MOTarrowIcon");
     if(arrow.src === 'https://localhost:7131/images/icons8-right-arrow-64.png'){
         arrow.src = 'https://localhost:7131/images/icons8-drop-down-64.png';
     } else {
         arrow.src = 'https://localhost:7131/images/icons8-right-arrow-64.png';
     }
}

 function IncorrectVehicleDetails() {

      var x = document.getElementById("incorrectVehicleDetailsInfo");
          if (x.style.display === "none") {
            x.style.display = "block";
          } else {
            x.style.display = "none";
          }

    var arrow = document.getElementById("incorrectDetailarrowIcon");
     if(arrow.src === 'https://localhost:7131/images/icons8-right-arrow-64.png'){
         arrow.src = 'https://localhost:7131/images/icons8-drop-down-64.png';
     } else {
         arrow.src = 'https://localhost:7131/images/icons8-right-arrow-64.png';
     }
}

</script>

CustomerApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AdminApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AdminApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-black border-bottom box-shadow mb-3" style="padding-left:340px">
            <div class="container-fluid">
                <a class="text-info"><img src="/images/crown-icon.png" alt="images" style="width:50px; height:50px;"/></a>
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index" style="padding-left: 15px">GOV.UK</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between" >
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item" >
                            <a id="return-to-homepage" class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       @* <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Create">Create</a>
                        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="position:fixed; bottom:0px;">
        <div class="container">
            &copy; 2023 - AdminApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>